### ISSUE TITLE
OpenSSL pre-build framework was built without full bitcode

### ISSUE THREAD

**Issue by xiaohanyeah** [OuterCorner/OpenSSL#1]
Hi, I got this error when archiving. "Release-iphoneos/OpenSSL.framework/OpenSSL' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build ...". It might because you upload the build files (-fembed-bitcode-marker) instead of the archive files (-fembed-bitcode). Could you release a new version of the pre-build framework? Thanks!

**Comment by jpulik** [comment]
Hi,
I've just proposed pull request for this. Let's see if it will be approved.
https://github.com/OuterCorner/OpenSSL/pull/2

**Comment by pfandrade** [comment]
Just merged it and released a new version.

**Comment by xiaohanyeah** [comment]
Thank you all for solving the issue!
