### ISSUE TITLE
Swift ignores CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES

### ISSUE THREAD

**Issue by knightcode** [OuterCorner/OpenSSL#4]
I was able to include the OpenSSL project as a dependency of my own project. And It builds fine on its own. However, as soon as I add `import OpenSSL` to a swift file, the build fails with an error saying
```
Include of non-modular header inside framework module 'OpenSSL.e_os2
```

No such error occurs in objective-c files because `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES`, but, once I include the obj-c class in the bridging header... same error.

There's a reference to a fix using a modulemap [here](https://github.com/x2on/OpenSSL-for-iPhone/issues/122), but I don't know what `Modules` folder they're referring to. And I'm not sure if the modulemap needs to be written to the src directory after it's unpacked or something.

There's also a suggestion of "just making the header file public" [here](https://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module), but not sure how to do that in this context with the scripting.

Perhaps related to this is that the Xcode editor is unable to find the declarations inside the framework. It doesn't complain about `import OpenSSL`, but it does complain about `EVP_CIPHER_CTX` not being found in both Swift and Obj-C. The build still succeeds despite this, so I'm guessing the headers aren't being found in the intermediates directory (or wherever the editor looks). The false errors are just clutter, which would be nice to remove. Or I'm not doing something I should be.

**Comment by pfandrade** [comment]
Can you try version 1.2.1?

**Comment by knightcode** [comment]
No problems with `import OpenSSL` directly in swift or via the bridging header, but, in both cases, I'm getting `Cannot find type 'EVP_CIPHER_CTX' in scope` and similar errors in the Swift code. And then the build fails with errors:
```
Could not read serialized diagnostics file: error("Invalid diagnostics signature")
Command CompileSwift failed with a nonzero exit code
```

In Obj-c, I'm having somewhat better luck. I get both errors like:
```Implicit declaration of function 'EVP_get_cipherbyname' is invalid in C99```
but also a warning about the return value of EVP_get_cipherbyname:
```Assigning to 'EVP_CIPHER *' (aka 'struct evp_cipher_st *') from 'const EVP_CIPHER *' (aka 'const struct evp_cipher_st *') discards qualifiers```

The build succeeds, though, with `@import OpenSSL;` in my `.h` file and the `.h` file included in the bridging header, which should let me build some Obj-c wrappers around the openssl API that I can then import into and use in Swift. Arguably, that's not a bad way to go in general, but I'd still like to clear all the bogus errors and warnings. It'd make it easier to know when the build is going to fail.

Am I doing something wrong?

I can also pull the HEAD of the master branch if you want me to try anything else before making another release.

**Comment by pfandrade** [comment]
I believe that's just how Swift is parsing those headers. ECP_CIPHER_CTX is just an OpaquePointer in Swift, but `EVP_CIPHER_CTX_new` is there and working.

Working with the OpenSSL directly in Swift is a bit of a pain, for [example](https://github.com/thebrankoo/CryptoLab/blob/b42b8bac1fc29d72dae331af48ce9dd1b040300f/CryptoLab/Cipher/CoreAES.swift#L124). So I usually wrap my interaction with it in ObjC and expose a friendlier interface to Swift.

**Comment by knightcode** [comment]
I'm game to work in Obj-c, and I get that all the functions are there. It's just there's still a ton of "implicit declaration of..." errors in the editor. There has to be something we can add to the Framework or Header Search Paths to satisfy them, right? If not, I can totally make do with this. This is great.

**Comment by pfandrade** [comment]
That's strange. I don't get any of those warnings. I use this extensively in ObjC and made a test project yesterday in Swift. Both showed no warnings.

**Comment by knightcode** [comment]
@pfandrade , how did you include this project as a dependency? Maybe I need to do it differently. I cloned this repo at tag 1.2.1, then pulled OpenSSL.xcodeproj into the workspace of my project as a top level sibling of my project and the Pods project. Then I was able to add "OpenSSL.framework" from that project as a dependency under General -> "Frameworks, Libraries, and Embedded Content" for my app. That allowed `@import OpenSSL;` to work in my `.h` file.

I also tried switching to "libopenssl.a" as the dependency with no change.

Under Build Settings -> "Framework Search Paths", there's a list of directories corresponding to the cocoapods I have as dependencies, ...but it doesn't list any for the dependencies from the SwiftPM. So not sure if adding anything there or to "Header Search Paths" would fix this for me.

**Comment by pfandrade** [comment]
I added it has an SPM dependency. Downloading the xcframework manually and adding it to the project also works fine. I don't usually have this as a project dependency because building OpenSSL takes a long time.

**Comment by knightcode** [comment]
ah... yeah, I need to build it locally for security purposes

**Comment by knightcode** [comment]
When trying to do a release build, it's throwing
```ld: library not found for -lopenssl```
This is when it tries to build the OpenSSL.framework target from the Project as a dependency. It works for Debug builds. Not sure why it's not working here. I haven't tried copying the xcframework into my project and building yet. Will try that tomorrow.

**Comment by knightcode** [comment]
Copying in the pre-built xcframework worked. I was able to archive my project.

App Store Connect doesn't like CFBundleShortVersionString = "1.1.1m" though. It must conform to semver.

**Comment by pfandrade** [comment]
Building locally is understandable. There's a script in Scripts that builds the XCframework.

And since you're building it locally you can also change the version info to get around that. Alternatively, just let Xcode do [it for you](https://stackoverflow.com/questions/68237292/manage-version-and-build-number).
